In [1]:
from pathlib import Path
import re
import pandas as pd
from collections import Counter
from tqdm import tqdm
import numpy as np

In [2]:
data_folder_path = Path("/home/pcallec/mif_outer/data/pig_kidney")

In [3]:
l_image_path = list(data_folder_path.rglob("*.jpg"))

In [4]:
l_image_path[:5]

[PosixPath('/home/pcallec/mif_outer/data/pig_kidney/k4/k4_medulla/180_k4_medulla.jpg'),
 PosixPath('/home/pcallec/mif_outer/data/pig_kidney/k4/k4_medulla/320_k4_medulla.jpg'),
 PosixPath('/home/pcallec/mif_outer/data/pig_kidney/k4/k4_medulla/342_k4_medulla.jpg'),
 PosixPath('/home/pcallec/mif_outer/data/pig_kidney/k4/k4_medulla/627_k4_medulla.jpg'),
 PosixPath('/home/pcallec/mif_outer/data/pig_kidney/k4/k4_medulla/350_k4_medulla.jpg')]

In [5]:
l_image_path[0].parts[-2]

'k4_medulla'

In [6]:
# filename,fold_name,relative_path,absolute_filepath,type
df_data = pd.DataFrame()
for image_path in tqdm(l_image_path):
    filename = image_path.name
    filename_stem = image_path.stem
    
    split_text = re.split(r'[_]', filename_stem)
    # e.g. ['39', 'k4', 'medulla']
    
    row_dict = pd.DataFrame({
        "filename":[filename],
        "absolute_filepath": [image_path],
        "fold_name": [split_text[1]],
        "category": [split_text[2]]
    })
    
    df_data = pd.concat([df_data, row_dict], ignore_index=True)

  3%|▎         | 928/30000 [00:00<00:06, 4594.49it/s]

100%|██████████| 30000/30000 [00:11<00:00, 2548.86it/s]

In [12]:
df_data["category"] = df_data["category"].replace({"pelvis": "pelvis-calyx"})

In [13]:
df_data["category"].unique()

array(['medulla', 'cortex', 'pelvis-calyx'], dtype=object)

In [16]:
l_category=["cortex", "medulla","pelvis-calyx"]

category_to_label = {category: label for label, category in enumerate(l_category)}
df_data['label'] = df_data['category'].map(category_to_label)
df_data.to_csv("/home/pcallec/analyze_images/results/pig_kidney/pig_kidney_metadata.csv", index=False)

In [17]:
df_data.head()

,filename,absolute_filepath,fold_name,category,label
0,180_k4_medulla.jpg,/home/pcallec/mif_outer/data/pig_kidney/k4/k4_...,k4,medulla,1
1,320_k4_medulla.jpg,/home/pcallec/mif_outer/data/pig_kidney/k4/k4_...,k4,medulla,1
2,342_k4_medulla.jpg,/home/pcallec/mif_outer/data/pig_kidney/k4/k4_...,k4,medulla,1
3,627_k4_medulla.jpg,/home/pcallec/mif_outer/data/pig_kidney/k4/k4_...,k4,medulla,1
4,350_k4_medulla.jpg,/home/pcallec/mif_outer/data/pig_kidney/k4/k4_...,k4,medulla,1

In [18]:
Counter(df_data["category"])

Counter({'medulla': 10000, 'cortex': 10000, 'pelvis-calyx': 10000})

In [22]:
df_data_stats = df_data.groupby(["fold_name", "category"]).size().reset_index(name='count')
df_data_stats

   fold_name      category  count
0         k1        cortex   1000
1         k1       medulla   1000
2         k1  pelvis-calyx   1000
3        k10        cortex   1000
4        k10       medulla   1000
5        k10  pelvis-calyx   1000
6         k2        cortex   1000
7         k2       medulla   1000
8         k2  pelvis-calyx   1000
9         k3        cortex   1000
10        k3       medulla   1000
11        k3  pelvis-calyx   1000
12        k4        cortex   1000
13        k4       medulla   1000
14        k4  pelvis-calyx   1000
15        k5        cortex   1000
16        k5       medulla   1000
17        k5  pelvis-calyx   1000
18        k6        cortex   1000
19        k6       medulla   1000
20        k6  pelvis-calyx   1000
21        k7        cortex   1000
22        k7       medulla   1000
23        k7  pelvis-calyx   1000
24        k8        cortex   1000
25        k8       medulla   1000
26        k8  pelvis-calyx   1000
27        k9        cortex   1000
28        k9       medulla   1000
29        k9  pelvis-calyx   1000

In [23]:
df_data_stats.to_csv("/home/pcallec/analyze_images/results/pig_kidney/pig_kidney_properties_stats.csv", index=False)

In [24]:
df_data.to_csv("/home/pcallec/analyze_images/results/pig_kidney/pig_kidney_properties.csv", index=False)

In [25]:
# Partition data into train, val, and test

df_data_stats

   fold_name      category  count
0         k1        cortex   1000
1         k1       medulla   1000
2         k1  pelvis-calyx   1000
3        k10        cortex   1000
4        k10       medulla   1000
5        k10  pelvis-calyx   1000
6         k2        cortex   1000
7         k2       medulla   1000
8         k2  pelvis-calyx   1000
9         k3        cortex   1000
10        k3       medulla   1000
11        k3  pelvis-calyx   1000
12        k4        cortex   1000
13        k4       medulla   1000
14        k4  pelvis-calyx   1000
15        k5        cortex   1000
16        k5       medulla   1000
17        k5  pelvis-calyx   1000
18        k6        cortex   1000
19        k6       medulla   1000
20        k6  pelvis-calyx   1000
21        k7        cortex   1000
22        k7       medulla   1000
23        k7  pelvis-calyx   1000
24        k8        cortex   1000
25        k8       medulla   1000
26        k8  pelvis-calyx   1000
27        k9        cortex   1000
28        k9       medulla   1000
29        k9  pelvis-calyx   1000